# サービス名はアルファベットとハイフンのみ
service: try-slack-slash-command

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  pythonRequirements:
    dockerizePip: true
  wsgi:
    app: app.app
    # serverless-python-requirementsを使うので、こちらはfalse
    packRequirements: false

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    # Lambdaから別Lambdaを呼び出すためのロールの設定
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
      Resource: ${ssm:/TFANDKUSU_TRY_SLACK_SLASH_COMMAND_WORKER_LAMBDA_ARN}

functions:
  app:
    # HTTPSサーバ相当のLambda
    handler: wsgi_handler.handler
    environment:
      TFANDKUSU_SLACK_SIGNING_SECRET: ${ssm:/TFANDKUSU_SLACK_SIGNING_SECRET}
    events:
      # API Gatewayの設定
      - http: ANY /
      - http: ANY /{proxy+}

  worker:
    # 非同期で実行したい時間がかかる処理のLambda
    handler: worker.handle
